# Generated by Django 5.1.8 on 2025-05-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_limit',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
