# Generated by Django 5.1.8 on 2025-05-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_client_user_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user_limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
