# Generated by Django 5.1.8 on 2025-05-13 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_client_user_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#007bff', max_length=7)),
                ('secondary_color', models.CharField(default='#28a745', max_length=7)),
                ('background_color', models.CharField(default='#f0f0f0', max_length=7)),
                ('font_family', models.CharField(default='Arial, sans-serif', max_length=100)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
        ),
    ]
