# Generated by Django 5.1.8 on 2025-05-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_theme_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='tenant',
        ),
        migrations.AddField(
            model_name='theme',
            name='theme_name',
            field=models.CharField(default='theme', max_length=35),
        ),
    ]
