# Generated by Django 5.1.8 on 2025-05-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_theme_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='tenant',
        ),
    ]
