# Generated by Django 5.1.8 on 2025-05-14 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_remove_theme_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='tenant',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='customers.client'),
            preserve_default=False,
        ),
    ]
