# Generated by Django 5.1.8 on 2025-05-14 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_theme_tenant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
