# Generated by Django 5.1.8 on 2025-05-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
