# Generated by Django 5.1.8 on 2025-05-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_delete_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('trial_days', models.PositiveIntegerField(default=7)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
