# Generated by Django 5.1.8 on 2025-05-19 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.plan'),
        ),
    ]
