# Generated by Django 5.1.8 on 2025-05-19 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.plan'),
        ),
    ]
