# Generated by Django 5.1.8 on 2025-05-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_payment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='price',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
