# Generated by Django 5.1.8 on 2025-05-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_remove_payment_plan_remove_payment_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
