# Generated by Django 5.1.8 on 2025-05-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='user_limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
