# Generated by Django 5.1.8 on 2025-05-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_plan_user_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user_limit',
        ),
    ]
