# Generated by Django 5.1.8 on 2025-05-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_remove_client_user_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
