# Generated by Django 5.1.8 on 2025-05-14 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_theme_tenant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
