# Generated by Django 5.1.8 on 2025-05-14 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='tenant',
        ),
    ]
